import { Inter } from "next/font/google";
import Navbar from "./Components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container px-4 mx-auto">
        <Navbar />
        {children}
        </div>
        </body>
    </html>
  );
}
